name: phase0_prototypes
description: Technical validation prototypes for Seasonal Quest Web App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # Google Maps Integration
  google_maps_flutter: ^2.13.1
  google_maps_flutter_web: ^0.5.14+2
  
  # Browser APIs
  image_picker_for_web: ^3.1.0
  geolocator: ^14.0.2
  geolocator_web: ^4.1.3
  shared_preferences: ^2.5.3
  shared_preferences_web: ^2.4.3
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
